- name: Add MongoDB public GPG key securely
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-6.0.asc
    dest: /usr/share/keyrings/mongodb-server-6.0.gpg
    mode: '0644'

- name: Add MongoDB 6.0 repository
  apt_repository:
    repo: "deb [ arch=amd64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"
    state: present
    filename: mongodb-org-6.0

- name: Install MongoDB
  apt:
    name: mongodb-org
    update_cache: yes
    state: present


- name: Start and enable MongoDB
  systemd:
    name: mongod
    state: started
    enabled: true

- name: Seed MongoDB with sample messages
  copy:
    dest: /tmp/seed.js
    content: |
      use securedb;
      db.messages.insertMany([
        { text: "Welcome to Team32!" },
        { text: "Your app is secured and verified." },
        { text: "Deployed using Ansible + Jenkins + Flask!" }
      ]);
      
- name: Run seed script
  shell: mongo /tmp/seed.js
