[app]
app-server ansible_host=172.31.1.149 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/saturday.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[agent]
jenkins-agent ansible_host=172.31.21.103 ansible_user=cloud-user ansible_ssh_private_key_file=/home/ec2-user/saturday.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
