---
# vars file for app_server
# ansible/group_vars/all.yml
domain: team32.org
certbot_email: oyewoleakanbi4@gmail.com

#vars for playbook dir
playbook_dir: "/home/ubuntu/jenkins-agent/workspace/flask-dev-app/ansible"