---
# roles/deploy_nginx/tasks/main.yml

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Allow Nginx through UFW
  ufw:
    rule: allow
    name: 'Nginx Full'

- name: Install Certbot and Nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Nginx config for {{ domain }}
  template:
    src: nginx_team32.conf.j2
    dest: /etc/nginx/sites-available/{{ domain }}

- name: Enable Nginx site for {{ domain }}
  file:
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    state: link

- name: Reload Nginx before Certbot
  service:
    name: nginx
    state: reloaded

- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: cert

- name: Obtain SSL certificate with Certbot for {{ domain }}
  command: >
    certbot --nginx --non-interactive --agree-tos --redirect
    --email {{ certbot_email }}
    -d {{ domain }} -d www.{{ domain }}
  when: not cert.stat.exists
  register: certbot_result
  changed_when: "'Congratulations' in certbot_result.stdout"
