- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install Flask and PyMongo
  pip:
    name:
      - Flask==2.3.2
      - pymongo==4.6.1
    state: present

- name: Upload app archive
  copy:
    src: "../app.tar.gz"
    dest: /tmp/app.tar.gz

- name: Upload hash file
  copy:
    src: "../hash.txt"
    dest: /tmp/hash.txt

- name: Verify SHA-256 hash
  shell: |
    cd /tmp
    sha256sum -c hash.txt
  register: hash_check
  failed_when: "'OK' not in hash_check.stdout"
  changed_when: false

- name: Create /opt/app directory
  file:
    path: /opt/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Extract app archive to /opt/app
  unarchive:
    src: /tmp/app.tar.gz
    dest: /opt/app
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create systemd service for Flask (Dev Server)
  copy:
    dest: /etc/systemd/system/flaskapp.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      User=ubuntu
      WorkingDirectory=/opt/app
      ExecStart=/usr/bin/python3 /opt/app/app.py
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Flask app
  systemd:
    name: flaskapp
    daemon_reload: true
    enabled: true
    state: restarted
