---
# tasks file for app_server
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install base packages
  apt:
    name:
      - python3
      - python3-pip
      - git
      - curl
      - unzip
      - ufw
    state: present

- name: Allow UFW for SSH and Web Ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
    - 5000

- name: Enable the firewall
  ufw:
    state: enabled
    policy: allow

- name: Ensure the 'ubuntu' user owns /opt/
  file:
    path: /opt
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
